// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

//Conecta tudo a um banco de dados
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBZx6MElJFLkbMeUPqLxuoP1UWvcRL7TtE",
    authDomain: "acacia-ca6e6.firebaseapp.com",
    projectId: "acacia-ca6e6",
    storageBucket: "acacia-ca6e6.firebasestorage.app",
    messagingSenderId: "361484085797",
    appId: "1:361484085797:web:62bc79c83d5d35a9b3adcc",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBZx6MElJFLkbMeUPqLxuoP1UWvcRL7TtE",
    authDomain: "acacia-ca6e6.firebaseapp.com",
    projectId: "acacia-ca6e6",
    storageBucket: "acacia-ca6e6.firebasestorage.app",
    messagingSenderId: "361484085797",
    appId: "1:361484085797:web:62bc79c83d5d35a9b3adcc",
  );
}
